### ISSUE TITLE
Error: Cannot find module 'tsconfig-glob'

### ISSUE THREAD

**Issue by jamesjwarren** [wjohnsto/tsconfig-lint#7]
Installed and tried to run on the command line with `tsconfig-lint .` but getting the following error:

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'tsconfig-glob'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/tsconfig-lint/index.js:10:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by wjohnsto** [comment]
This is fixed in v0.10.2
